save-position-on-quit=yes
alang=eng,en
slang=eng,en
window-maximized=yes

# Subtitle jump works with cache
cache=yes
cache-secs=60

# some cache help
# Increase how much data mpv can buffer overall
demuxer-max-bytes=500MiB      # ~500 MB cache

# Increase backward cache
demuxer-max-back-bytes=200MiB

# Don’t pause playback when the cache underruns
cache-pause=no

# Let seeking use the cache when possible
demuxer-seekable-cache=auto


# input conf

s ignore

